version: "3.2"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      data-network:
        aliases:
          - postgres
  redis:
    image: redis:5.0.3
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      data-network:
        aliases:
          - redis

volumes:
  postgres-data:
  
networks:
  data-network: